// Front-end/RPG0010 - Meu primeiro framework/livros-react/src/livroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ControleEditora from './controle/controleEditora';
import ControleLivros from './controle/controleLivro';

// Instanciando classes
const controleEditora = new ControleEditora()
const controleLivro = new ControleLivros()

const LivroDados = () => {
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(1); // Inicializada com a posição um para que seja a alta books
    const navigate = useNavigate();
  
    const opcoes = controleEditora.getEditoras().map(editora => {
      return(
        {
          value: editora.codEditora,
          text: editora.nome,
        }
      )
    });
  
    const tratarCombo = (event) => {
      setCodEditora(Number(event.target.value));
    };
  
    const incluir = (event) => {
      event.preventDefault();
      const autoresArray = autores.split('\n');
      const novoLivro = {
        codigo: 0, // Código inicializado com zero
        titulo,
        resumo,
        autores: autoresArray,
        codEditora,
      };
      controleLivro.incluir(novoLivro);
      navigate('/');
    };
  
    return (
        // main
      <main className='container'>
        <h2>Incluir Livro</h2>

        {/* formulario */}
        <form onSubmit={incluir} className='w-20'>

            {/* input */}
          <div className="form-group">
            <label>Título:</label>
            <input type="text" className="form-control " value={titulo} onChange={(e) => setTitulo(e.target.value)} required/>
          </div>

          {/* textarea */}
          <div className="form-group">
            <label>Resumo:</label>
            <textarea className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} required ></textarea>
          </div>

          {/* Autores */}
          <div className="form-group">
            <label>Autores:</label>
            <textarea className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} required ></textarea>
          </div>

          {/* Select editoras */}
          <div className="form-group">
            <label>Editora:</label>
            <select
              className="form-control"
              value={codEditora}
              onChange={tratarCombo}
            >
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
              ))}
            </select>
          </div>

          {/* button incluir */}
            <button className=" btn btn-primary mt-2 py-0">Adicionar</button>
        </form>
      </main>
    );
  };

export default LivroDados

// Front-end/RPG0012 - Vamos colocar o framework para acessar um banco/Clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import Livro from '../livro';
import Editora from '../editora';
import ControleEditoraService from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit{
  // Definindo propriedades
  livro: Livro = new Livro('',0,'','',[]);
  autoresForm: string = '';
  editoras: Editora[] = [];

  // constructor
  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  // oninit
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  // incluindo livro
  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n').map((author) => author.trim())
    
    this.servLivros.incluir(this.livro).then(() => {
      this.router.navigateByUrl('/lista');
    })
  };
}

<div class="container">
    <!--   titulo da pagina-->
    <h2>Dados do Livro</h2>

    <!-- formulario -->
    <form>

        <!-- inputs -->
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo">
      </div>

      <!-- inputs -->
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>

      <!-- inputs -->
      <div class="form-group">
        <label for="codEditora">Editora:</label>
        <select class="form-control" id="codEditora" [(ngModel)]="livro.codEditora" name="codEditora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>

      <!-- inputs -->
      <div class="form-group">
        <label for="autoresForm">Autores (separados por quebras de linha):</label>
        <textarea class="form-control" id="autoresForm" [(ngModel)]="autoresForm" name="autoresForm"></textarea>
      </div>
      
      <!-- inputs -->
      <button class="btn btn-primary" (click)="incluir()">Incluir Livro</button>
    </form>
</div>
